# Site settings
title: Orion Analytics
description: Jekyll Theme Minimal Resume

# User settings
username: Orion Analytics
user_description: We are here to save the world
user_title: Dissolves bottlenecks of your business
email: t.eliseeva@web.de

exclude: ['package.json', 'src' , 'node_modules']
