# Site settings
title: Orion Analytics
description: Jekyll Theme Minimal Resume

# User settings
username: Antares Analytics
user_description: Orion Analytics delivers scallable solutions and digital products for your business
user_title: Expert in processing your data
email: t.eliseeva@web.de

exclude: ['package.json', 'src' , 'node_modules']
