# Site settings
title: Antares Analytics
description: Jekyll Theme Minimal Resume

# User settings
username: Antares Analytics
user_description: Antares Analytics delivers scallable solutions and digital products for your business
user_title: 
email: t.eliseeva@web.de

exclude: ['package.json', 'src' , 'node_modules']
