# Site settings
title: Antares Analytics
description: Jekyll Theme Minimal Resume

# User settings
username: Antares Analytics
user_description: 
user_title: 
email: contact@antaresanalytics.de

exclude: ['package.json', 'src' , 'node_modules']
